### ISSUE TITLE
TypeError: Path must be a string

### ISSUE THREAD

**Issue by swillard-r7** [jshanson7/babel-plugin-resolver#2]
Upgraded to 0.0.7 and I'm getting:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at posix.resolve (path.js:426:5)
    at Plugin.ResolverPlugin.manipulateOptions (/Users/swillard/Documents/github/cardbuilder-js/node_modules/babel-plugin-resolver/lib/ResolverPlugin.js:14:27)
    at File.buildPlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:255:16)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:135:10)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transform (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:53:22)
    at Object.compile (/usr/local/lib/node_modules/babel-cli/lib/babel/util.js:62:12)
    at write (/usr/local/lib/node_modules/babel-cli/lib/babel/dir.js:19:21)
    at handleFile (/usr/local/lib/node_modules/babel-cli/lib/babel/dir.js:42:7)

```

My config:

```
    [ "resolver", {
      "resolveDirs": ["src", "src/js"]
    }],
```

Things seem fine in 0.0.5

**Comment by gnestor** [comment]
I'm getting a similar error when using babel-node (REPL):

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:9:11)
    at posix.resolve (path.js:427:5)
    at Plugin.ResolverPlugin.manipulateOptions (/Users/grant/Sites/whammy/aws.whammy/node_modules/babel-plugin-resolver/lib/ResolverPlugin.js:14:27)
    at File.buildPlugins (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:255:16)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:135:10)
    at Pipeline.transform (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at _eval (/usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:96:16)
    at REPLServer.replEval (/usr/local/lib/node_modules/babel-cli/lib/_babel-node.js:187:14)
    at bound (domain.js:281:14)
    at REPLServer.runBound [as eval] (domain.js:294:12)
```

**Comment by vince-roy** [comment]
Issue was resolved for me when changing the following in lib/ResolverPlugin :
var nodeModulesPaths = findNodeModulesPaths(__dirname)
to
var nodeModulesPaths = findNodeModulesPath(__dirname)

I think the old version of babel-resolver uses findNodeModulesPath versus findNodeModulesPaths in the new version.

**Comment by vdh** [comment]
I'm running into this issue, but only on a Windows 10 setup. No sign (yet) of the issue appearing on my Mac OS X setup.

.babelrc is

```
{
  "plugins": [
    "transform-runtime",
    "transform-object-rest-spread",
    ["resolver", { "resolveDirs": ["."] }]
  ],
  "presets": ["react", "es2015", "stage-0"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    }
  }
}
```

Rolling back to version 0.0.6 appears to avoid the issue for now.

**Comment by jeffhandley** [comment]
I was seeing this same issue.  :+1: for version 0.0.6 working though.

**Comment by StevenLangbroek** [comment]
ping @jshanson7

**Comment by iongion** [comment]
Is this going to be addressed ?
